version: '3.9'
services:
  weather-api:
    container_name: weather-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8000:8000
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.test
    restart: on-failure
    depends_on:
      - weather-api
    links:
      - weather-api